name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build site
        run: echo "Build step goes here"

      - name: Deploy
        run: echo "Deploy step goes here"
